In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
delhi = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Delhi_combined_refined.csv", index_col="Timestamp", parse_dates=True)
mumbai = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Mumbai_combined_refined.csv", index_col="Timestamp", parse_dates=True)
kolkata = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Kolkata_combined_refined.csv", parse_dates=True)
bengaluru = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Bengaluru_combined_refined.csv", index_col="Timestamp", parse_dates=True)

In [57]:
delhi = delhi.round(2)

In [69]:
delhi = delhi.reset_index()

In [70]:
delhi["City"] = "Delhi"

In [71]:
cols = list(delhi.columns)
cols.insert(cols.index("Timestamp")+1, cols.pop(cols.index("City")))
delhi = delhi[cols]

In [72]:
delhi = delhi.set_index("Timestamp")

In [73]:
delhi

,City,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,Ozone,...,MP-Xylene,AT,RH,WS,WD,RF,TOT-RF,SR,BP,VWS
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,Delhi,393.56,598.82,214.12,99.19,222.79,41.48,21.34,3.31,9.63,...,NaN,13.97,75.32,0.32,230.10,NaN,0.0,157.49,974.07,NaN
2022-01-02,Delhi,424.81,598.95,228.46,96.99,258.12,40.60,27.42,1.90,11.58,...,NaN,14.33,75.32,0.32,230.36,NaN,0.0,153.11,974.16,NaN
2022-01-03,Delhi,375.52,636.12,199.10,109.72,237.60,42.33,19.10,2.31,8.47,...,NaN,14.79,72.44,0.35,223.51,NaN,0.0,153.24,973.69,NaN
2022-01-04,Delhi,291.86,564.58,227.86,96.62,247.82,45.26,20.05,1.81,11.73,...,NaN,16.14,66.95,0.31,209.49,NaN,0.0,144.70,973.12,NaN
2022-01-05,Delhi,353.05,449.37,118.76,60.40,128.94,37.73,15.30,1.65,25.07,...,NaN,14.45,86.60,0.89,138.08,NaN,0.0,77.72,973.50,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,Delhi,201.56,240.34,56.41,93.86,95.78,98.62,6.33,1.29,7.82,...,NaN,13.85,85.92,1.60,240.99,NaN,0.0,18.47,740.51,NaN
2024-12-28,Delhi,111.92,151.11,93.26,97.74,127.79,82.53,11.67,1.37,2.61,...,NaN,13.98,90.09,0.60,212.98,NaN,0.0,31.43,740.03,NaN
2024-12-29,Delhi,123.29,178.12,57.66,75.84,87.24,72.08,1.54,1.23,3.85,...,NaN,13.84,84.74,1.05,222.97,NaN,0.0,41.78,740.00,NaN
2024-12-30,Delhi,106.01,181.87,49.98,67.24,76.41,57.98,4.70,1.64,4.57,...,NaN,12.87,79.71,1.03,194.38,NaN,0.0,55.83,739.99,NaN
2024-12-31,Delhi,236.47,380.20,68.07,70.94,93.08,58.20,9.51,2.39,5.52,...,NaN,13.02,74.44,0.84,238.19,NaN,0.0,61.56,740.08,NaN

In [74]:
mumbai= mumbai.round(2)

In [75]:
mumbai = mumbai.reset_index()

In [64]:
mumbai["City"]= "Mumbai"

In [76]:
cols = list(mumbai.columns)
cols.insert(cols.index("Timestamp")+1, cols.pop(cols.index("City")))
mumbai = mumbai[cols]

In [77]:
mumbai = mumbai.set_index("Timestamp")

In [78]:
mumbai

,City,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,Ozone,...,MP-Xylene,AT,RH,WS,WD,RF,TOT-RF,SR,BP,VWS
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,Mumbai,52.26,111.27,0.92,8.50,9.42,8.50,22.33,0.77,16.18,...,0.28,25.18,70.19,1.92,147.86,NaN,0.0,0.02,998.24,NaN
2022-01-02,Mumbai,56.66,120.21,4.81,9.35,14.16,8.49,23.32,0.90,16.53,...,0.90,24.24,72.96,1.94,136.70,NaN,0.0,0.02,998.24,NaN
2022-01-03,Mumbai,61.15,123.23,5.12,9.06,14.18,8.65,26.14,0.99,16.37,...,0.89,24.53,73.72,1.92,157.24,NaN,0.0,0.01,998.24,NaN
2022-01-04,Mumbai,86.90,154.63,6.33,12.13,18.46,9.28,30.55,1.25,16.23,...,1.37,24.28,76.55,1.92,151.91,NaN,0.0,0.01,998.24,NaN
2022-01-05,Mumbai,74.61,151.99,5.00,9.69,14.69,8.45,32.57,1.09,16.27,...,0.70,24.08,79.91,1.95,176.14,NaN,0.0,0.01,998.24,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,Mumbai,59.28,93.41,12.39,20.31,32.70,1.98,8.37,0.50,10.73,...,0.79,29.85,98.57,4.22,156.63,NaN,0.0,0.01,1014.92,NaN
2024-12-28,Mumbai,82.26,112.49,12.58,20.64,33.22,2.01,8.37,0.50,10.64,...,0.79,29.59,99.41,4.23,128.51,NaN,0.0,0.01,1014.88,NaN
2024-12-29,Mumbai,74.69,101.41,12.98,21.29,34.27,2.08,8.36,0.52,10.72,...,0.79,30.29,99.40,4.17,143.56,NaN,0.0,0.01,1014.70,NaN
2024-12-30,Mumbai,46.77,71.90,11.69,19.18,30.87,1.87,8.37,0.47,10.81,...,0.79,30.97,98.59,4.11,155.48,NaN,0.0,0.01,1014.59,NaN
2024-12-31,Mumbai,51.95,78.63,12.30,20.18,32.48,1.97,8.37,0.49,10.95,...,0.79,31.42,98.42,4.14,157.82,NaN,0.0,0.01,1014.96,NaN

In [79]:
kolkata= kolkata.round(2)

In [80]:
kolkata = kolkata.reset_index()

In [81]:
kolkata["City"] = "Kolkata"

In [82]:
cols = list(kolkata.columns)
cols.insert(cols.index("Timestamp")+1, cols.pop(cols.index("City")))
kolkata = kolkata[cols]

In [83]:
kolkata = kolkata.set_index("Timestamp")

In [43]:
kolkata

,City,index,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,...,MP-Xylene,AT,RH,WS,WD,RF,TOT-RF,SR,BP,VWS
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,Kolkata,0,113.29,190.47,9.32,26.51,35.83,16.48,46.57,0.73,...,2.00,30.82,75.78,0.20,234.69,0.0,0.0,67.49,999.41,0.00
2022-01-02,Kolkata,1,121.76,201.37,10.02,26.41,36.39,15.16,28.85,0.84,...,1.23,30.82,89.76,0.23,250.62,0.0,0.0,67.56,999.41,-0.00
2022-01-03,Kolkata,2,129.84,224.62,12.66,29.13,41.79,15.40,30.50,0.90,...,2.13,30.82,76.83,0.15,193.59,0.0,0.0,62.28,999.41,-0.00
2022-01-04,Kolkata,3,170.97,258.60,8.44,27.49,35.94,16.28,38.08,0.97,...,1.83,30.82,75.66,0.17,169.55,0.0,0.0,66.11,999.41,-0.00
2022-01-05,Kolkata,4,182.03,277.74,9.88,28.17,38.13,16.41,29.77,1.13,...,3.62,30.82,75.02,0.12,188.90,0.0,0.0,66.10,999.41,-0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,Kolkata,1091,57.02,148.71,17.09,28.55,42.92,19.00,7.33,0.85,...,2.26,21.46,55.59,0.24,159.74,0.0,0.0,106.61,1023.45,2.64
2024-12-28,Kolkata,1092,67.65,164.72,25.93,38.04,61.26,16.86,7.11,0.90,...,3.23,20.93,59.05,0.12,187.41,0.0,0.0,106.94,1022.15,2.24
2024-12-29,Kolkata,1093,74.64,186.42,26.76,40.60,64.65,15.13,7.08,1.00,...,4.24,21.67,59.00,0.13,190.58,0.0,0.0,103.10,1021.24,1.88
2024-12-30,Kolkata,1094,78.44,155.79,15.05,28.51,40.84,17.87,7.82,0.81,...,2.67,21.88,61.78,0.21,187.62,0.0,0.0,101.68,1021.89,2.06
2024-12-31,Kolkata,1095,72.62,132.30,10.43,21.16,28.88,16.44,9.31,0.64,...,0.57,19.31,69.14,0.46,159.13,0.0,0.0,146.34,1023.10,3.10

In [84]:
kolkata = kolkata.drop(columns=["index"])

In [85]:
kolkata

,City,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,Ozone,...,MP-Xylene,AT,RH,WS,WD,RF,TOT-RF,SR,BP,VWS
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,Kolkata,113.29,190.47,9.32,26.51,35.83,16.48,46.57,0.73,36.97,...,2.00,30.82,75.78,0.20,234.69,0.0,0.0,67.49,999.41,0.00
2022-01-02,Kolkata,121.76,201.37,10.02,26.41,36.39,15.16,28.85,0.84,26.63,...,1.23,30.82,89.76,0.23,250.62,0.0,0.0,67.56,999.41,-0.00
2022-01-03,Kolkata,129.84,224.62,12.66,29.13,41.79,15.40,30.50,0.90,30.98,...,2.13,30.82,76.83,0.15,193.59,0.0,0.0,62.28,999.41,-0.00
2022-01-04,Kolkata,170.97,258.60,8.44,27.49,35.94,16.28,38.08,0.97,39.07,...,1.83,30.82,75.66,0.17,169.55,0.0,0.0,66.11,999.41,-0.00
2022-01-05,Kolkata,182.03,277.74,9.88,28.17,38.13,16.41,29.77,1.13,39.82,...,3.62,30.82,75.02,0.12,188.90,0.0,0.0,66.10,999.41,-0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,Kolkata,57.02,148.71,17.09,28.55,42.92,19.00,7.33,0.85,50.26,...,2.26,21.46,55.59,0.24,159.74,0.0,0.0,106.61,1023.45,2.64
2024-12-28,Kolkata,67.65,164.72,25.93,38.04,61.26,16.86,7.11,0.90,32.03,...,3.23,20.93,59.05,0.12,187.41,0.0,0.0,106.94,1022.15,2.24
2024-12-29,Kolkata,74.64,186.42,26.76,40.60,64.65,15.13,7.08,1.00,32.53,...,4.24,21.67,59.00,0.13,190.58,0.0,0.0,103.10,1021.24,1.88
2024-12-30,Kolkata,78.44,155.79,15.05,28.51,40.84,17.87,7.82,0.81,36.18,...,2.67,21.88,61.78,0.21,187.62,0.0,0.0,101.68,1021.89,2.06
2024-12-31,Kolkata,72.62,132.30,10.43,21.16,28.88,16.44,9.31,0.64,40.31,...,0.57,19.31,69.14,0.46,159.13,0.0,0.0,146.34,1023.10,3.10

In [86]:
bengaluru = bengaluru.round(2)

In [87]:
bengaluru = bengaluru.reset_index()

In [88]:
bengaluru["City"] = "Bengaluru"

In [89]:
cols = list(bengaluru.columns)
cols.insert(cols.index("Timestamp")+1, cols.pop(cols.index("City")))
bengaluru = bengaluru[cols]

In [90]:
bengaluru = bengaluru.set_index("Timestamp")

In [91]:
bengaluru

,City,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,Ozone,...,MP-Xylene,AT,RH,WS,WD,RF,TOT-RF,SR,BP,VWS
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,Bengaluru,13.50,28.36,18.91,16.08,33.00,2.30,7.01,0.10,18.76,...,0.30,NaN,83.92,0.93,191.38,NaN,NaN,54.71,923.25,0.04
2022-01-02,Bengaluru,12.67,27.15,18.92,16.08,33.00,2.30,6.99,0.10,19.68,...,0.30,NaN,93.33,0.93,86.44,NaN,NaN,73.18,921.95,0.07
2022-01-03,Bengaluru,12.67,27.15,18.92,16.08,33.00,2.30,6.99,0.10,19.68,...,0.30,NaN,93.33,0.93,86.44,NaN,NaN,73.18,921.95,0.07
2022-01-04,Bengaluru,12.67,27.15,18.92,16.08,33.00,2.30,6.99,0.10,19.68,...,0.30,NaN,93.33,0.93,86.44,NaN,NaN,73.18,921.95,0.07
2022-01-05,Bengaluru,12.67,27.15,18.92,16.08,33.00,2.30,6.99,0.10,19.68,...,0.30,NaN,93.33,0.93,86.44,NaN,NaN,73.18,921.95,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,Bengaluru,23.97,44.23,8.35,36.76,45.11,14.45,15.56,0.58,21.17,...,0.89,NaN,93.86,0.97,229.80,NaN,NaN,45.96,951.78,-0.76
2024-12-28,Bengaluru,28.65,53.01,8.12,36.06,44.18,14.21,15.51,0.54,21.30,...,0.89,NaN,86.98,1.03,225.94,NaN,NaN,53.02,946.25,-0.77
2024-12-29,Bengaluru,29.46,58.98,8.36,37.16,45.52,14.31,15.64,0.65,21.21,...,0.89,NaN,81.78,1.04,236.57,NaN,NaN,53.56,943.18,-0.76
2024-12-30,Bengaluru,28.08,55.98,7.75,34.75,42.50,14.06,14.40,0.61,22.71,...,0.81,NaN,89.24,1.08,235.84,NaN,NaN,50.66,943.14,-0.77
2024-12-31,Bengaluru,33.41,56.89,8.26,37.05,45.31,14.26,11.89,0.55,23.01,...,0.79,NaN,76.49,0.99,237.13,NaN,NaN,52.89,939.94,-0.76

In [118]:
data= pd.concat([delhi, mumbai, kolkata, bengaluru])

In [119]:
data.to_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\All_combined.csv")

In [124]:
data = data.reset_index()

In [125]:
data = data.sort_values(by=["Timestamp", "City"])

In [126]:
data = data.set_index("Timestamp")

In [127]:
data

,City,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,Ozone,...,MP-Xylene,AT,RH,WS,WD,RF,TOT-RF,SR,BP,VWS
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,Bengaluru,13.50,28.36,18.91,16.08,33.00,2.30,7.01,0.10,18.76,...,0.30,NaN,83.92,0.93,191.38,NaN,NaN,54.71,923.25,0.04
2022-01-01,Delhi,393.56,598.82,214.12,99.19,222.79,41.48,21.34,3.31,9.63,...,NaN,13.97,75.32,0.32,230.10,NaN,0.0,157.49,974.07,NaN
2022-01-01,Kolkata,113.29,190.47,9.32,26.51,35.83,16.48,46.57,0.73,36.97,...,2.00,30.82,75.78,0.20,234.69,0.0,0.0,67.49,999.41,0.00
2022-01-01,Mumbai,52.26,111.27,0.92,8.50,9.42,8.50,22.33,0.77,16.18,...,0.28,25.18,70.19,1.92,147.86,NaN,0.0,0.02,998.24,NaN
2022-01-02,Bengaluru,12.67,27.15,18.92,16.08,33.00,2.30,6.99,0.10,19.68,...,0.30,NaN,93.33,0.93,86.44,NaN,NaN,73.18,921.95,0.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-30,Mumbai,46.77,71.90,11.69,19.18,30.87,1.87,8.37,0.47,10.81,...,0.79,30.97,98.59,4.11,155.48,NaN,0.0,0.01,1014.59,NaN
2024-12-31,Bengaluru,33.41,56.89,8.26,37.05,45.31,14.26,11.89,0.55,23.01,...,0.79,NaN,76.49,0.99,237.13,NaN,NaN,52.89,939.94,-0.76
2024-12-31,Delhi,236.47,380.20,68.07,70.94,93.08,58.20,9.51,2.39,5.52,...,NaN,13.02,74.44,0.84,238.19,NaN,0.0,61.56,740.08,NaN
2024-12-31,Kolkata,72.62,132.30,10.43,21.16,28.88,16.44,9.31,0.64,40.31,...,0.57,19.31,69.14,0.46,159.13,0.0,0.0,146.34,1023.10,3.10
2024-12-31,Mumbai,51.95,78.63,12.30,20.18,32.48,1.97,8.37,0.49,10.95,...,0.79,31.42,98.42,4.14,157.82,NaN,0.0,0.01,1014.96,NaN

In [128]:
data.index

DatetimeIndex(['2022-01-01', '2022-01-01', '2022-01-01', '2022-01-01',
               '2022-01-02', '2022-01-02', '2022-01-02', '2022-01-02',
               '2022-01-03', '2022-01-03',
               ...
               '2024-12-29', '2024-12-29', '2024-12-30', '2024-12-30',
               '2024-12-30', '2024-12-30', '2024-12-31', '2024-12-31',
               '2024-12-31', '2024-12-31'],
              dtype='datetime64[us]', name='Timestamp', length=4384, freq=None)

In [130]:
data.index.dtype

dtype('<M8[us]')

In [131]:
data.to_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\All_combined(sorted).csv")