In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
Del22 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\AnandViharDelhi2022.csv", index_col="Timestamp", parse_dates=True)
Del23 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\AnandViharDelhi2023.csv", index_col="Timestamp", parse_dates=True)
Del24 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\AnandViharDelhi2024.csv", index_col="Timestamp", parse_dates=True)

In [6]:
delhi = pd.concat([Del22, Del23, Del24])
delhi

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,393.56,598.82,214.12,99.19,222.79,41.48,21.34,3.31,9.63,6.40,...,NaN,13.97,75.32,0.32,230.10,NaN,0.0,157.49,974.07,NaN
2022-01-02,424.81,598.95,228.46,96.99,258.12,40.60,27.42,1.90,11.58,7.07,...,NaN,14.33,75.32,0.32,230.36,NaN,0.0,153.11,974.16,NaN
2022-01-03,375.52,636.12,199.10,109.72,237.60,42.33,19.10,2.31,8.47,7.93,...,NaN,14.79,72.44,0.35,223.51,NaN,0.0,153.24,973.69,NaN
2022-01-04,291.86,564.58,227.86,96.62,247.82,45.26,20.05,1.81,11.73,6.89,...,NaN,16.14,66.95,0.31,209.49,NaN,0.0,144.70,973.12,NaN
2022-01-05,353.05,449.37,118.76,60.40,128.94,37.73,15.30,1.65,25.07,NaN,...,NaN,14.45,86.60,0.89,138.08,NaN,0.0,77.72,973.50,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,201.56,240.34,56.41,93.86,95.78,98.62,6.33,1.29,7.82,4.87,...,NaN,13.85,85.92,1.60,240.99,NaN,0.0,18.47,740.51,NaN
2024-12-28,111.92,151.11,93.26,97.74,127.79,82.53,11.67,1.37,2.61,4.28,...,NaN,13.98,90.09,0.60,212.98,NaN,0.0,31.43,740.03,NaN
2024-12-29,123.29,178.12,57.66,75.84,87.24,72.08,1.54,1.23,3.85,2.80,...,NaN,13.84,84.74,1.05,222.97,NaN,0.0,41.78,740.00,NaN
2024-12-30,106.01,181.87,49.98,67.24,76.41,57.98,4.70,1.64,4.57,2.15,...,NaN,12.87,79.71,1.03,194.38,NaN,0.0,55.83,739.99,NaN
2024-12-31,236.47,380.20,68.07,70.94,93.08,58.20,9.51,2.39,5.52,4.22,...,NaN,13.02,74.44,0.84,238.19,NaN,0.0,61.56,740.08,NaN

In [7]:
delhi.shape

(1096, 24)

In [8]:
delhi.size

26304

In [9]:
delhi.columns

Index(['PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)', 'NO2 (µg/m³)',
       'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)',
       'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)',
       'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)',
       'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)',
       'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)'],
      dtype='str')

In [10]:
delhi.index.duplicated().sum()

np.int64(0)

In [11]:
delhi.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1096 entries, 2022-01-01 to 2024-12-31
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PM2.5 (µg/m³)        1064 non-null   float64
 1   PM10 (µg/m³)         1059 non-null   float64
 2   NO (µg/m³)           1050 non-null   float64
 3   NO2 (µg/m³)          1050 non-null   float64
 4   NOx (ppb)            1055 non-null   float64
 5   NH3 (µg/m³)          1055 non-null   float64
 6   SO2 (µg/m³)          1050 non-null   float64
 7   CO (mg/m³)           1026 non-null   float64
 8   Ozone (µg/m³)        1058 non-null   float64
 9   Benzene (µg/m³)      874 non-null    float64
 10  Toluene (µg/m³)      872 non-null    float64
 11  Xylene (µg/m³)       0 non-null      float64
 12  O Xylene (µg/m³)     0 non-null      float64
 13  Eth-Benzene (µg/m³)  0 non-null      float64
 14  MP-Xylene (µg/m³)    0 non-null      float64
 15  AT (°C)              1063 non-null   float64
 16  RH (%)               1063 non-null   float64
 17  WS (m/s)             1054 non-null   float64
 18  WD (deg)             1063 non-null   float64
 19  RF (mm)              0 non-null      float64
 20  TOT-RF (mm)          1096 non-null   float64
 21  SR (W/mt2)           1066 non-null   float64
 22  BP (mmHg)            929 non-null    float64
 23  VWS (m/s)            0 non-null      float64
dtypes: float64(24)
memory usage: 214.1 KB

In [12]:
delhi= delhi.sort_index()
delhi

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,393.56,598.82,214.12,99.19,222.79,41.48,21.34,3.31,9.63,6.40,...,NaN,13.97,75.32,0.32,230.10,NaN,0.0,157.49,974.07,NaN
2022-01-02,424.81,598.95,228.46,96.99,258.12,40.60,27.42,1.90,11.58,7.07,...,NaN,14.33,75.32,0.32,230.36,NaN,0.0,153.11,974.16,NaN
2022-01-03,375.52,636.12,199.10,109.72,237.60,42.33,19.10,2.31,8.47,7.93,...,NaN,14.79,72.44,0.35,223.51,NaN,0.0,153.24,973.69,NaN
2022-01-04,291.86,564.58,227.86,96.62,247.82,45.26,20.05,1.81,11.73,6.89,...,NaN,16.14,66.95,0.31,209.49,NaN,0.0,144.70,973.12,NaN
2022-01-05,353.05,449.37,118.76,60.40,128.94,37.73,15.30,1.65,25.07,NaN,...,NaN,14.45,86.60,0.89,138.08,NaN,0.0,77.72,973.50,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,201.56,240.34,56.41,93.86,95.78,98.62,6.33,1.29,7.82,4.87,...,NaN,13.85,85.92,1.60,240.99,NaN,0.0,18.47,740.51,NaN
2024-12-28,111.92,151.11,93.26,97.74,127.79,82.53,11.67,1.37,2.61,4.28,...,NaN,13.98,90.09,0.60,212.98,NaN,0.0,31.43,740.03,NaN
2024-12-29,123.29,178.12,57.66,75.84,87.24,72.08,1.54,1.23,3.85,2.80,...,NaN,13.84,84.74,1.05,222.97,NaN,0.0,41.78,740.00,NaN
2024-12-30,106.01,181.87,49.98,67.24,76.41,57.98,4.70,1.64,4.57,2.15,...,NaN,12.87,79.71,1.03,194.38,NaN,0.0,55.83,739.99,NaN
2024-12-31,236.47,380.20,68.07,70.94,93.08,58.20,9.51,2.39,5.52,4.22,...,NaN,13.02,74.44,0.84,238.19,NaN,0.0,61.56,740.08,NaN

In [51]:
delhi.to_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Delhi_combined.csv", index=True)

In [13]:
delhi.isnull().sum()

PM2.5 (µg/m³)            32
PM10 (µg/m³)             37
NO (µg/m³)               46
NO2 (µg/m³)              46
NOx (ppb)                41
NH3 (µg/m³)              41
SO2 (µg/m³)              46
CO (mg/m³)               70
Ozone (µg/m³)            38
Benzene (µg/m³)         222
Toluene (µg/m³)         224
Xylene (µg/m³)         1096
O Xylene (µg/m³)       1096
Eth-Benzene (µg/m³)    1096
MP-Xylene (µg/m³)      1096
AT (°C)                  33
RH (%)                   33
WS (m/s)                 42
WD (deg)                 33
RF (mm)                1096
TOT-RF (mm)               0
SR (W/mt2)               30
BP (mmHg)               167
VWS (m/s)              1096
dtype: int64

In [14]:
(delhi.isnull().sum() / len(delhi)) * 100

PM2.5 (µg/m³)            2.919708
PM10 (µg/m³)             3.375912
NO (µg/m³)               4.197080
NO2 (µg/m³)              4.197080
NOx (ppb)                3.740876
NH3 (µg/m³)              3.740876
SO2 (µg/m³)              4.197080
CO (mg/m³)               6.386861
Ozone (µg/m³)            3.467153
Benzene (µg/m³)         20.255474
Toluene (µg/m³)         20.437956
Xylene (µg/m³)         100.000000
O Xylene (µg/m³)       100.000000
Eth-Benzene (µg/m³)    100.000000
MP-Xylene (µg/m³)      100.000000
AT (°C)                  3.010949
RH (%)                   3.010949
WS (m/s)                 3.832117
WD (deg)                 3.010949
RF (mm)                100.000000
TOT-RF (mm)              0.000000
SR (W/mt2)               2.737226
BP (mmHg)               15.237226
VWS (m/s)              100.000000
dtype: float64

In [15]:
delhi.columns = delhi.columns.str.split(" ").str[0]
delhi.isnull().sum()

PM2.5            32
PM10             37
NO               46
NO2              46
NOx              41
NH3              41
SO2              46
CO               70
Ozone            38
Benzene         222
Toluene         224
Xylene         1096
O              1096
Eth-Benzene    1096
MP-Xylene      1096
AT               33
RH               33
WS               42
WD               33
RF             1096
TOT-RF            0
SR               30
BP              167
VWS            1096
dtype: int64

In [16]:
delhi= delhi.ffill()
delhi= delhi.bfill()

In [17]:
delhi.isnull().sum()

PM2.5             0
PM10              0
NO                0
NO2               0
NOx               0
NH3               0
SO2               0
CO                0
Ozone             0
Benzene           0
Toluene           0
Xylene         1096
O              1096
Eth-Benzene    1096
MP-Xylene      1096
AT                0
RH                0
WS                0
WD                0
RF             1096
TOT-RF            0
SR                0
BP                0
VWS            1096
dtype: int64

In [63]:
delhi.to_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Delhi_combined_refined.csv", index=True)

In [18]:
Mumb22 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\ColabaMumbai2022.csv", index_col="Timestamp", parse_dates=True)
Mumb23 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\ColabaMumbai2023.csv", index_col="Timestamp", parse_dates=True)
Mumb24 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\ColabaMumbai2024.csv", index_col="Timestamp", parse_dates=True)

In [19]:
mumbai = pd.concat([Mumb22, Mumb23, Mumb24])
mumbai

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,52.26,111.27,0.92,8.50,9.42,8.50,22.33,0.77,16.18,0.38,...,0.28,25.18,70.19,1.92,147.86,NaN,0.0,NaN,NaN,NaN
2022-01-02,56.66,120.21,4.81,9.35,14.16,8.49,23.32,0.90,16.53,0.61,...,0.90,24.24,72.96,1.94,136.70,NaN,0.0,0.02,NaN,NaN
2022-01-03,61.15,123.23,5.12,9.06,14.18,8.65,26.14,0.99,16.37,0.67,...,0.89,24.53,73.72,1.92,157.24,NaN,0.0,0.01,NaN,NaN
2022-01-04,86.90,154.63,6.33,12.13,18.46,9.28,30.55,1.25,16.23,2.35,...,1.37,24.28,76.55,1.92,151.91,NaN,0.0,0.01,NaN,NaN
2022-01-05,74.61,151.99,5.00,9.69,14.69,8.45,32.57,1.09,16.27,3.44,...,0.70,24.08,79.91,1.95,176.14,NaN,0.0,0.01,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,59.28,93.41,12.39,20.31,32.70,1.98,8.37,0.50,10.73,0.00,...,NaN,29.85,98.57,4.22,156.63,NaN,0.0,NaN,1014.92,NaN
2024-12-28,82.26,112.49,12.58,20.64,33.22,2.01,8.37,0.50,10.64,0.00,...,NaN,29.59,99.41,4.23,128.51,NaN,0.0,NaN,1014.88,NaN
2024-12-29,74.69,101.41,12.98,21.29,34.27,2.08,8.36,0.52,10.72,0.00,...,NaN,30.29,99.40,4.17,143.56,NaN,0.0,NaN,1014.70,NaN
2024-12-30,46.77,71.90,11.69,19.18,30.87,1.87,8.37,0.47,10.81,0.00,...,NaN,30.97,98.59,4.11,155.48,NaN,0.0,NaN,1014.59,NaN
2024-12-31,51.95,78.63,12.30,20.18,32.48,1.97,8.37,0.49,10.95,0.00,...,NaN,31.42,98.42,4.14,157.82,NaN,0.0,NaN,1014.96,NaN

In [20]:
mumbai.shape

(1096, 24)

In [21]:
mumbai.size

26304

In [22]:
mumbai.columns

Index(['PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)', 'NO2 (µg/m³)',
       'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)',
       'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)',
       'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)',
       'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)',
       'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)'],
      dtype='str')

In [23]:
mumbai.index.duplicated().sum()

np.int64(0)

In [24]:
mumbai.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1096 entries, 2022-01-01 to 2024-12-31
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PM2.5 (µg/m³)        967 non-null    float64
 1   PM10 (µg/m³)         1039 non-null   float64
 2   NO (µg/m³)           954 non-null    float64
 3   NO2 (µg/m³)          931 non-null    float64
 4   NOx (ppb)            998 non-null    float64
 5   NH3 (µg/m³)          995 non-null    float64
 6   SO2 (µg/m³)          987 non-null    float64
 7   CO (mg/m³)           1044 non-null   float64
 8   Ozone (µg/m³)        1045 non-null   float64
 9   Benzene (µg/m³)      1043 non-null   float64
 10  Toluene (µg/m³)      0 non-null      float64
 11  Xylene (µg/m³)       0 non-null      float64
 12  O Xylene (µg/m³)     0 non-null      float64
 13  Eth-Benzene (µg/m³)  636 non-null    float64
 14  MP-Xylene (µg/m³)    636 non-null    float64
 15  AT (°C)              1029 non-null   float64
 16  RH (%)               1042 non-null   float64
 17  WS (m/s)             1043 non-null   float64
 18  WD (deg)             1043 non-null   float64
 19  RF (mm)              0 non-null      float64
 20  TOT-RF (mm)          1096 non-null   float64
 21  SR (W/mt2)           178 non-null    float64
 22  BP (mmHg)            849 non-null    float64
 23  VWS (m/s)            0 non-null      float64
dtypes: float64(24)
memory usage: 214.1 KB

In [25]:
mumbai= mumbai.sort_index()
mumbai

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,52.26,111.27,0.92,8.50,9.42,8.50,22.33,0.77,16.18,0.38,...,0.28,25.18,70.19,1.92,147.86,NaN,0.0,NaN,NaN,NaN
2022-01-02,56.66,120.21,4.81,9.35,14.16,8.49,23.32,0.90,16.53,0.61,...,0.90,24.24,72.96,1.94,136.70,NaN,0.0,0.02,NaN,NaN
2022-01-03,61.15,123.23,5.12,9.06,14.18,8.65,26.14,0.99,16.37,0.67,...,0.89,24.53,73.72,1.92,157.24,NaN,0.0,0.01,NaN,NaN
2022-01-04,86.90,154.63,6.33,12.13,18.46,9.28,30.55,1.25,16.23,2.35,...,1.37,24.28,76.55,1.92,151.91,NaN,0.0,0.01,NaN,NaN
2022-01-05,74.61,151.99,5.00,9.69,14.69,8.45,32.57,1.09,16.27,3.44,...,0.70,24.08,79.91,1.95,176.14,NaN,0.0,0.01,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,59.28,93.41,12.39,20.31,32.70,1.98,8.37,0.50,10.73,0.00,...,NaN,29.85,98.57,4.22,156.63,NaN,0.0,NaN,1014.92,NaN
2024-12-28,82.26,112.49,12.58,20.64,33.22,2.01,8.37,0.50,10.64,0.00,...,NaN,29.59,99.41,4.23,128.51,NaN,0.0,NaN,1014.88,NaN
2024-12-29,74.69,101.41,12.98,21.29,34.27,2.08,8.36,0.52,10.72,0.00,...,NaN,30.29,99.40,4.17,143.56,NaN,0.0,NaN,1014.70,NaN
2024-12-30,46.77,71.90,11.69,19.18,30.87,1.87,8.37,0.47,10.81,0.00,...,NaN,30.97,98.59,4.11,155.48,NaN,0.0,NaN,1014.59,NaN
2024-12-31,51.95,78.63,12.30,20.18,32.48,1.97,8.37,0.49,10.95,0.00,...,NaN,31.42,98.42,4.14,157.82,NaN,0.0,NaN,1014.96,NaN

In [76]:
mumbai.to_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Mumbai_combined.csv", index=True)

In [26]:
mumbai.isnull().sum()

PM2.5 (µg/m³)           129
PM10 (µg/m³)             57
NO (µg/m³)              142
NO2 (µg/m³)             165
NOx (ppb)                98
NH3 (µg/m³)             101
SO2 (µg/m³)             109
CO (mg/m³)               52
Ozone (µg/m³)            51
Benzene (µg/m³)          53
Toluene (µg/m³)        1096
Xylene (µg/m³)         1096
O Xylene (µg/m³)       1096
Eth-Benzene (µg/m³)     460
MP-Xylene (µg/m³)       460
AT (°C)                  67
RH (%)                   54
WS (m/s)                 53
WD (deg)                 53
RF (mm)                1096
TOT-RF (mm)               0
SR (W/mt2)              918
BP (mmHg)               247
VWS (m/s)              1096
dtype: int64

In [27]:
(mumbai.isnull().sum()/len(mumbai))*100

PM2.5 (µg/m³)           11.770073
PM10 (µg/m³)             5.200730
NO (µg/m³)              12.956204
NO2 (µg/m³)             15.054745
NOx (ppb)                8.941606
NH3 (µg/m³)              9.215328
SO2 (µg/m³)              9.945255
CO (mg/m³)               4.744526
Ozone (µg/m³)            4.653285
Benzene (µg/m³)          4.835766
Toluene (µg/m³)        100.000000
Xylene (µg/m³)         100.000000
O Xylene (µg/m³)       100.000000
Eth-Benzene (µg/m³)     41.970803
MP-Xylene (µg/m³)       41.970803
AT (°C)                  6.113139
RH (%)                   4.927007
WS (m/s)                 4.835766
WD (deg)                 4.835766
RF (mm)                100.000000
TOT-RF (mm)              0.000000
SR (W/mt2)              83.759124
BP (mmHg)               22.536496
VWS (m/s)              100.000000
dtype: float64

In [28]:
mumbai.columns = mumbai.columns.str.split(" ").str[0]
mumbai.isnull().sum()

PM2.5           129
PM10             57
NO              142
NO2             165
NOx              98
NH3             101
SO2             109
CO               52
Ozone            51
Benzene          53
Toluene        1096
Xylene         1096
O              1096
Eth-Benzene     460
MP-Xylene       460
AT               67
RH               54
WS               53
WD               53
RF             1096
TOT-RF            0
SR              918
BP              247
VWS            1096
dtype: int64

In [29]:
mumbai= mumbai.ffill()
mumbai= mumbai.bfill()

In [30]:
mumbai.isnull().sum()

PM2.5             0
PM10              0
NO                0
NO2               0
NOx               0
NH3               0
SO2               0
CO                0
Ozone             0
Benzene           0
Toluene        1096
Xylene         1096
O              1096
Eth-Benzene       0
MP-Xylene         0
AT                0
RH                0
WS                0
WD                0
RF             1096
TOT-RF            0
SR                0
BP                0
VWS            1096
dtype: int64

In [87]:
mumbai.to_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Mumbai_combined_refined.csv", index=True)

In [31]:
Kolkt22 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\RabindraBharatiKolkata2022.csv", index_col="Timestamp", parse_dates=True)
Kolkt23 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\RabindraBharatiKolkata2023.csv", index_col="Timestamp", parse_dates=True)
Kolkt24 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\RabindraBharatiKolkata2024.csv", index_col="Timestamp", parse_dates=True)

In [32]:
kolkata= pd.concat([Kolkt22, Kolkt23, Kolkt24])
kolkata

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,113.29,190.47,9.32,26.51,35.83,16.48,46.57,0.73,36.97,3.94,...,2.00,NaN,75.78,0.20,234.69,NaN,0.0,67.49,NaN,0.00
2022-01-02,121.76,201.37,10.02,26.41,36.39,15.16,28.85,0.84,26.63,3.52,...,1.23,NaN,89.76,0.23,250.62,NaN,0.0,67.56,NaN,-0.00
2022-01-03,129.84,224.62,12.66,29.13,41.79,15.40,30.50,0.90,30.98,4.09,...,2.13,NaN,76.83,0.15,193.59,NaN,0.0,62.28,NaN,-0.00
2022-01-04,170.97,258.60,8.44,27.49,35.94,16.28,38.08,0.97,39.07,5.02,...,1.83,NaN,75.66,0.17,169.55,NaN,0.0,66.11,NaN,-0.00
2022-01-05,182.03,277.74,9.88,28.17,38.13,16.41,29.77,1.13,39.82,7.79,...,3.62,NaN,75.02,0.12,188.90,NaN,0.0,66.10,NaN,-0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,57.02,148.71,17.09,28.55,42.92,19.00,7.33,0.85,50.26,3.81,...,2.26,21.46,55.59,0.24,159.74,0.0,0.0,106.61,1023.45,2.64
2024-12-28,67.65,164.72,25.93,38.04,61.26,16.86,7.11,0.90,32.03,5.66,...,3.23,20.93,59.05,0.12,187.41,0.0,0.0,106.94,1022.15,2.24
2024-12-29,74.64,186.42,26.76,40.60,64.65,15.13,7.08,1.00,32.53,6.52,...,4.24,21.67,59.00,0.13,190.58,0.0,0.0,103.10,1021.24,1.88
2024-12-30,78.44,155.79,15.05,28.51,40.84,17.87,7.82,0.81,36.18,4.61,...,2.67,21.88,61.78,0.21,187.62,0.0,0.0,101.68,1021.89,2.06
2024-12-31,72.62,132.30,10.43,21.16,28.88,16.44,9.31,0.64,40.31,2.13,...,0.57,19.31,69.14,0.46,159.13,0.0,0.0,146.34,1023.10,3.10

In [33]:
kolkata.shape

(1096, 24)

In [34]:
kolkata.size

26304

In [35]:
kolkata.columns

Index(['PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)', 'NO2 (µg/m³)',
       'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)',
       'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)',
       'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)',
       'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)',
       'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)'],
      dtype='str')

In [36]:
kolkata.index.duplicated().sum()

np.int64(0)

In [37]:
kolkata.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1096 entries, 2022-01-01 to 2024-12-31
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PM2.5 (µg/m³)        1081 non-null   float64
 1   PM10 (µg/m³)         1081 non-null   float64
 2   NO (µg/m³)           1061 non-null   float64
 3   NO2 (µg/m³)          1060 non-null   float64
 4   NOx (ppb)            1062 non-null   float64
 5   NH3 (µg/m³)          1060 non-null   float64
 6   SO2 (µg/m³)          1080 non-null   float64
 7   CO (mg/m³)           1079 non-null   float64
 8   Ozone (µg/m³)        1078 non-null   float64
 9   Benzene (µg/m³)      1081 non-null   float64
 10  Toluene (µg/m³)      1081 non-null   float64
 11  Xylene (µg/m³)       0 non-null      float64
 12  O Xylene (µg/m³)     0 non-null      float64
 13  Eth-Benzene (µg/m³)  843 non-null    float64
 14  MP-Xylene (µg/m³)    1081 non-null   float64
 15  AT (°C)              843 non-null    float64
 16  RH (%)               1081 non-null   float64
 17  WS (m/s)             1081 non-null   float64
 18  WD (deg)             1081 non-null   float64
 19  RF (mm)              843 non-null    float64
 20  TOT-RF (mm)          1096 non-null   float64
 21  SR (W/mt2)           1080 non-null   float64
 22  BP (mmHg)            997 non-null    float64
 23  VWS (m/s)            1080 non-null   float64
dtypes: float64(24)
memory usage: 214.1 KB

In [38]:
kolkata= kolkata.sort_index()
kolkata

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,113.29,190.47,9.32,26.51,35.83,16.48,46.57,0.73,36.97,3.94,...,2.00,NaN,75.78,0.20,234.69,NaN,0.0,67.49,NaN,0.00
2022-01-02,121.76,201.37,10.02,26.41,36.39,15.16,28.85,0.84,26.63,3.52,...,1.23,NaN,89.76,0.23,250.62,NaN,0.0,67.56,NaN,-0.00
2022-01-03,129.84,224.62,12.66,29.13,41.79,15.40,30.50,0.90,30.98,4.09,...,2.13,NaN,76.83,0.15,193.59,NaN,0.0,62.28,NaN,-0.00
2022-01-04,170.97,258.60,8.44,27.49,35.94,16.28,38.08,0.97,39.07,5.02,...,1.83,NaN,75.66,0.17,169.55,NaN,0.0,66.11,NaN,-0.00
2022-01-05,182.03,277.74,9.88,28.17,38.13,16.41,29.77,1.13,39.82,7.79,...,3.62,NaN,75.02,0.12,188.90,NaN,0.0,66.10,NaN,-0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,57.02,148.71,17.09,28.55,42.92,19.00,7.33,0.85,50.26,3.81,...,2.26,21.46,55.59,0.24,159.74,0.0,0.0,106.61,1023.45,2.64
2024-12-28,67.65,164.72,25.93,38.04,61.26,16.86,7.11,0.90,32.03,5.66,...,3.23,20.93,59.05,0.12,187.41,0.0,0.0,106.94,1022.15,2.24
2024-12-29,74.64,186.42,26.76,40.60,64.65,15.13,7.08,1.00,32.53,6.52,...,4.24,21.67,59.00,0.13,190.58,0.0,0.0,103.10,1021.24,1.88
2024-12-30,78.44,155.79,15.05,28.51,40.84,17.87,7.82,0.81,36.18,4.61,...,2.67,21.88,61.78,0.21,187.62,0.0,0.0,101.68,1021.89,2.06
2024-12-31,72.62,132.30,10.43,21.16,28.88,16.44,9.31,0.64,40.31,2.13,...,0.57,19.31,69.14,0.46,159.13,0.0,0.0,146.34,1023.10,3.10

In [114]:
kolkata.to_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Kolkata_combined.csv", index=True)

In [39]:
kolkata.isnull().sum()

PM2.5 (µg/m³)            15
PM10 (µg/m³)             15
NO (µg/m³)               35
NO2 (µg/m³)              36
NOx (ppb)                34
NH3 (µg/m³)              36
SO2 (µg/m³)              16
CO (mg/m³)               17
Ozone (µg/m³)            18
Benzene (µg/m³)          15
Toluene (µg/m³)          15
Xylene (µg/m³)         1096
O Xylene (µg/m³)       1096
Eth-Benzene (µg/m³)     253
MP-Xylene (µg/m³)        15
AT (°C)                 253
RH (%)                   15
WS (m/s)                 15
WD (deg)                 15
RF (mm)                 253
TOT-RF (mm)               0
SR (W/mt2)               16
BP (mmHg)                99
VWS (m/s)                16
dtype: int64

In [40]:
(kolkata.isnull().sum()/len(kolkata))*100

PM2.5 (µg/m³)            1.368613
PM10 (µg/m³)             1.368613
NO (µg/m³)               3.193431
NO2 (µg/m³)              3.284672
NOx (ppb)                3.102190
NH3 (µg/m³)              3.284672
SO2 (µg/m³)              1.459854
CO (mg/m³)               1.551095
Ozone (µg/m³)            1.642336
Benzene (µg/m³)          1.368613
Toluene (µg/m³)          1.368613
Xylene (µg/m³)         100.000000
O Xylene (µg/m³)       100.000000
Eth-Benzene (µg/m³)     23.083942
MP-Xylene (µg/m³)        1.368613
AT (°C)                 23.083942
RH (%)                   1.368613
WS (m/s)                 1.368613
WD (deg)                 1.368613
RF (mm)                 23.083942
TOT-RF (mm)              0.000000
SR (W/mt2)               1.459854
BP (mmHg)                9.032847
VWS (m/s)                1.459854
dtype: float64

In [41]:
kolkata.columns = kolkata.columns.str.split(" ").str[0]
kolkata.isnull().sum()

PM2.5            15
PM10             15
NO               35
NO2              36
NOx              34
NH3              36
SO2              16
CO               17
Ozone            18
Benzene          15
Toluene          15
Xylene         1096
O              1096
Eth-Benzene     253
MP-Xylene        15
AT              253
RH               15
WS               15
WD               15
RF              253
TOT-RF            0
SR               16
BP               99
VWS              16
dtype: int64

In [42]:
kolkata= kolkata.ffill()
kolkata= kolkata.bfill()

In [43]:
kolkata.isnull().sum()

PM2.5             0
PM10              0
NO                0
NO2               0
NOx               0
NH3               0
SO2               0
CO                0
Ozone             0
Benzene           0
Toluene           0
Xylene         1096
O              1096
Eth-Benzene       0
MP-Xylene         0
AT                0
RH                0
WS                0
WD                0
RF                0
TOT-RF            0
SR                0
BP                0
VWS               0
dtype: int64

In [115]:
kolkata.to_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Kolkata_combined_refined.csv", index=True)

In [44]:
Beng22 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\BTMLayoutBengaluru2022.csv", index_col="Timestamp", parse_dates=True)
Beng23 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\BTMLayoutBengaluru2023.csv", index_col="Timestamp", parse_dates=True)
Beng24 = pd.read_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\BTMLayoutBengaluru2024.csv", index_col="Timestamp", parse_dates=True)

In [45]:
bengaluru= pd.concat([Beng22, Beng23, Beng24])
bengaluru

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,13.50,28.36,18.91,16.08,33.00,2.30,7.01,0.10,18.76,0.50,...,0.30,NaN,83.92,0.93,191.38,NaN,NaN,54.71,923.25,0.04
2022-01-02,12.67,27.15,18.92,16.08,33.00,2.30,6.99,0.10,19.68,0.50,...,0.30,NaN,93.33,0.93,86.44,NaN,NaN,73.18,921.95,0.07
2022-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,23.97,44.23,8.35,36.76,45.11,14.45,15.56,0.58,21.17,0.86,...,0.89,NaN,93.86,0.97,229.80,NaN,NaN,45.96,951.78,-0.76
2024-12-28,28.65,53.01,8.12,36.06,44.18,14.21,15.51,0.54,21.30,0.86,...,0.89,NaN,86.98,1.03,225.94,NaN,NaN,53.02,946.25,-0.77
2024-12-29,29.46,58.98,8.36,37.16,45.52,14.31,15.64,0.65,21.21,0.86,...,0.89,NaN,81.78,1.04,236.57,NaN,NaN,53.56,943.18,-0.76
2024-12-30,28.08,55.98,7.75,34.75,42.50,14.06,14.40,0.61,22.71,0.89,...,0.81,NaN,89.24,1.08,235.84,NaN,NaN,50.66,943.14,-0.77
2024-12-31,33.41,56.89,8.26,37.05,45.31,14.26,11.89,0.55,23.01,0.86,...,0.79,NaN,76.49,0.99,237.13,NaN,NaN,52.89,939.94,-0.76

In [46]:
bengaluru.shape

(1096, 24)

In [47]:
bengaluru.size

26304

In [48]:
bengaluru.columns

Index(['PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)', 'NO2 (µg/m³)',
       'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)',
       'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)',
       'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)',
       'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)',
       'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)'],
      dtype='str')

In [49]:
bengaluru.index.duplicated().sum()

np.int64(0)

In [50]:
bengaluru.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 1096 entries, 2022-01-01 to 2024-12-31
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PM2.5 (µg/m³)        1019 non-null   float64
 1   PM10 (µg/m³)         1020 non-null   float64
 2   NO (µg/m³)           1023 non-null   float64
 3   NO2 (µg/m³)          1023 non-null   float64
 4   NOx (ppb)            1024 non-null   float64
 5   NH3 (µg/m³)          1024 non-null   float64
 6   SO2 (µg/m³)          1040 non-null   float64
 7   CO (mg/m³)           1036 non-null   float64
 8   Ozone (µg/m³)        1041 non-null   float64
 9   Benzene (µg/m³)      1041 non-null   float64
 10  Toluene (µg/m³)      1041 non-null   float64
 11  Xylene (µg/m³)       0 non-null      float64
 12  O Xylene (µg/m³)     0 non-null      float64
 13  Eth-Benzene (µg/m³)  1038 non-null   float64
 14  MP-Xylene (µg/m³)    1038 non-null   float64
 15  AT (°C)              0 non-null      float64
 16  RH (%)               1024 non-null   float64
 17  WS (m/s)             823 non-null    float64
 18  WD (deg)             823 non-null    float64
 19  RF (mm)              0 non-null      float64
 20  TOT-RF (mm)          0 non-null      float64
 21  SR (W/mt2)           1024 non-null   float64
 22  BP (mmHg)            999 non-null    float64
 23  VWS (m/s)            1024 non-null   float64
dtypes: float64(24)
memory usage: 214.1 KB

In [51]:
bengaluru= bengaluru.sort_index()
bengaluru

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
Timestamp,,,,,,,,,,,,,,,,,,,,,
2022-01-01,13.50,28.36,18.91,16.08,33.00,2.30,7.01,0.10,18.76,0.50,...,0.30,NaN,83.92,0.93,191.38,NaN,NaN,54.71,923.25,0.04
2022-01-02,12.67,27.15,18.92,16.08,33.00,2.30,6.99,0.10,19.68,0.50,...,0.30,NaN,93.33,0.93,86.44,NaN,NaN,73.18,921.95,0.07
2022-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-27,23.97,44.23,8.35,36.76,45.11,14.45,15.56,0.58,21.17,0.86,...,0.89,NaN,93.86,0.97,229.80,NaN,NaN,45.96,951.78,-0.76
2024-12-28,28.65,53.01,8.12,36.06,44.18,14.21,15.51,0.54,21.30,0.86,...,0.89,NaN,86.98,1.03,225.94,NaN,NaN,53.02,946.25,-0.77
2024-12-29,29.46,58.98,8.36,37.16,45.52,14.31,15.64,0.65,21.21,0.86,...,0.89,NaN,81.78,1.04,236.57,NaN,NaN,53.56,943.18,-0.76
2024-12-30,28.08,55.98,7.75,34.75,42.50,14.06,14.40,0.61,22.71,0.89,...,0.81,NaN,89.24,1.08,235.84,NaN,NaN,50.66,943.14,-0.77
2024-12-31,33.41,56.89,8.26,37.05,45.31,14.26,11.89,0.55,23.01,0.86,...,0.79,NaN,76.49,0.99,237.13,NaN,NaN,52.89,939.94,-0.76

In [130]:
bengaluru.to_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Bengaluru_combined.csv", index=True)

In [52]:
bengaluru.isnull().sum()

PM2.5 (µg/m³)            77
PM10 (µg/m³)             76
NO (µg/m³)               73
NO2 (µg/m³)              73
NOx (ppb)                72
NH3 (µg/m³)              72
SO2 (µg/m³)              56
CO (mg/m³)               60
Ozone (µg/m³)            55
Benzene (µg/m³)          55
Toluene (µg/m³)          55
Xylene (µg/m³)         1096
O Xylene (µg/m³)       1096
Eth-Benzene (µg/m³)      58
MP-Xylene (µg/m³)        58
AT (°C)                1096
RH (%)                   72
WS (m/s)                273
WD (deg)                273
RF (mm)                1096
TOT-RF (mm)            1096
SR (W/mt2)               72
BP (mmHg)                97
VWS (m/s)                72
dtype: int64

In [53]:
(bengaluru.isnull().sum()/len(bengaluru))*100

PM2.5 (µg/m³)            7.025547
PM10 (µg/m³)             6.934307
NO (µg/m³)               6.660584
NO2 (µg/m³)              6.660584
NOx (ppb)                6.569343
NH3 (µg/m³)              6.569343
SO2 (µg/m³)              5.109489
CO (mg/m³)               5.474453
Ozone (µg/m³)            5.018248
Benzene (µg/m³)          5.018248
Toluene (µg/m³)          5.018248
Xylene (µg/m³)         100.000000
O Xylene (µg/m³)       100.000000
Eth-Benzene (µg/m³)      5.291971
MP-Xylene (µg/m³)        5.291971
AT (°C)                100.000000
RH (%)                   6.569343
WS (m/s)                24.908759
WD (deg)                24.908759
RF (mm)                100.000000
TOT-RF (mm)            100.000000
SR (W/mt2)               6.569343
BP (mmHg)                8.850365
VWS (m/s)                6.569343
dtype: float64

In [54]:
bengaluru.columns = bengaluru.columns.str.split(" ").str[0]
bengaluru.isnull().sum()

PM2.5            77
PM10             76
NO               73
NO2              73
NOx              72
NH3              72
SO2              56
CO               60
Ozone            55
Benzene          55
Toluene          55
Xylene         1096
O              1096
Eth-Benzene      58
MP-Xylene        58
AT             1096
RH               72
WS              273
WD              273
RF             1096
TOT-RF         1096
SR               72
BP               97
VWS              72
dtype: int64

In [55]:
bengaluru= bengaluru.ffill()
bengaluru= bengaluru.bfill()

In [56]:
bengaluru.isnull().sum()

PM2.5             0
PM10              0
NO                0
NO2               0
NOx               0
NH3               0
SO2               0
CO                0
Ozone             0
Benzene           0
Toluene           0
Xylene         1096
O              1096
Eth-Benzene       0
MP-Xylene         0
AT             1096
RH                0
WS                0
WD                0
RF             1096
TOT-RF         1096
SR                0
BP                0
VWS               0
dtype: int64

In [137]:
bengaluru.to_csv(r"C:\Users\DELL\Downloads\AQI_PROJECT\Bengaluru_combined_refined.csv", index=True)